FROM remote-host

COPY ./conf/nginx.repo /etc/apt/sources.list.d/nginx.list

ENV DEBIAN_FRONTEND=noninteractive

# Importar la clave GPG pública de Nginx
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ABF5BD827BD9BF62

RUN                                                                          \
 apt-get update &&                                                          \
 apt-get -y install nginx-full openssl php-fpm php-mysql php-soap php-xml php-json php-mbstring php-zip php-gd --no-install-recommends && \
 apt-get install -y acl && \
 apt-get clean all

EXPOSE 80 443

VOLUME /var/www/html /var/log/nginx /var/log/php-fpm /var/lib/php-fpm

RUN setfacl -R -m u:remote_user:rwx /var/www/html

COPY ./conf/nginx.conf /etc/nginx/site-available/default

COPY ./bin/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh
